# Name of the Workflow.
name: First Action

# Setter's. When the action will run.
on:
    workflow_dispatch:
        # Inputs the workflow accepts
        inputs:
            name:
                description: "Person to Greet!"
                # Default value should be there if no value is provided
                default: "World"
                # Input has to be provided for the wokflow to run
                required: true
                # Input type(string, choice, boolean)
                type: string
            city:
                description: "Favorite City"

                required: true

                default: "Pune"

                type: choice

                options:
                    - Mumbai
                    - Udupi
                    - Manglore
                    - Banglore
            favorite_color:
                description: "Is your favorite color Blue?"

                required: true
                
                type: boolean
            
jobs:
    # Job Name
    greet:
        # Display name for the job
        name: "First Action Greeting!"
        # The type of runer on which the job will run on
        runs-on:
            - ubuntu-latest 
        # Sequence of tasks that will be executed as part of job
        steps:
            - name: Congratulate!
              run: |
                echo "Hello! ${{github.event.inputs.name}}"
                echo "Your Favorite city is ${{github.event.inputs.city}}"
                echo "Your Favorite color is Blue: ${{github.event.inputs.favorite_color}}"