name: GitHub Context with objects and variables

on:
    workflow_dispatch:
        inputs:
            name:
                description: "Person to Greet!"
                default: "World"
                required: true
                type: string

env:
    var1: myworkflowvar1
    var2: myworkflowvar2
    var3: myworkflowvar3

jobs:
    job1:
        name: GitHub Context Output
        runs-on: 
            - ubuntu-latest
        steps:
            - name: GitHub Context
              env: 
                GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"

    job2:
        name: Storing Output Variable
        runs-on: 
            - ubuntu-latest

        outputs:
            output1: ${{ steps.step1.outputs.step1value }}
            output2: ${{ steps.step2.outputs.step2value }}

        steps:
            - name: Step 1
              id: step1
              run: echo "step1value=hello" << $GITHUB_OUTPUT
            
            - name: Step 2
              id: step2
              run: echo "step2value=world" << $GITHUB_OUTPUT

    job3:
        name: Print Output from Job 2
        runs-on: 
            - ubuntu-latest
        needs:
            - job2
        steps:
            - name: Print Output from Job 2
              run: echo ${{ needs.job2.outputs.output1 }} ${{ needs.job2.outputs.output2 }}

    job4:
        name: Nested Enviornment
        runs-on: 
            - ubuntu-latest

        env:
            var2: myvar2
            var3: myvar3

        steps:
            - name: Print Enviornment Variables
              run: |
                echo $var1
                echo ${{env.var1}}
                echo $var2
                echo $var3
              env:
                var3: myvariable3